#!/bin/bash
        sudo apt update
        sudo apt -y upgrade
        sudo apt -y dist-upgrade
        sudo snap refresh
        sudo apt clean -y
        sudo apt autoclean -y
        sudo apt autoremove -y
